### ISSUE TITLE
epilog cmd doesn't provide a target

### ISSUE THREAD

**Issue by nsheff** [databio/dnameth_pipelines#14]
```
Changed status from running to failed.
Traceback (most recent call last):
  File "/home/ns5bc/code/dnameth_pipelines/src/rrbs.py", line 677, in <module>
    main(sys.argv[1:])
  File "/home/ns5bc/code/dnameth_pipelines/src/rrbs.py", line 569, in main
    pm.run(epi_cmd, nofail=True)
  File "/home/ns5bc/.local/lib/python2.7/site-packages/pypiper/manager.py", line 611, in run
    "You must provide either a target or a lock_name."))
  File "/home/ns5bc/.local/lib/python2.7/site-packages/pypiper/manager.py", line 1575, in fail_pipeline
    raise e
Exception: You must provide either a target or a lock_name.
```

**Comment by vreuter** [comment]
Yeah the eventual solution will rely on what's implemented in the tool itself. In the meantime, the solution would be something like `os.path.join(<outfolder>, "all_calls.txt")` as the target

**Comment by vreuter** [comment]
Reraised in #20
