### ISSUE TITLE
paired end bug

### ISSUE THREAD

**Issue by nsheff** [databio/dnameth_pipelines#8]
```
### Adapter trimming:  (10-25 10:43:56) elapsed: 650.0 _TIME_

Traceback (most recent call last):
  File "/home/ns5bc/code/dnameth_pipelines/src/rrbs.py", line 651, in <module>
    main(sys.argv[1:])
  File "/home/ns5bc/code/dnameth_pipelines/src/rrbs.py", line 108, in main
    cmd = tools.python + " -u " + os.path.join(tools.scripts_dir, "detect_quality_code.py") + " -f " + unaligned_fastq
TypeError: cannot concatenate 'str' and 'list' objects
```

I think `unaligned_fastq` becomes a list when doing paired end...

**Comment by nsheff** [comment]
Fixed this.
